### ISSUE TITLE
/us/bin/ld: cannot find -lippicv

### ISSUE THREAD

**Issue by mmyros** [arnefmeyer/FrameGrabberPlugin#1]
Hello,

My colleague is trying to install this plugin and gets an error during compilation:
/us/bin/ld: cannot find -lippicv

I am not sure how opencv was installed, but the error seems to be related to opencv installation, right? Any pointers to fixing it without recompiling opencv? 

Also, in addition to CoreServices.h and CoreServices.cpp, we had to replace int64 with juce::int64 in GenericProcessor.h, maybe this deserves a mention in documentation.

Thanks!

**Comment by arnefmeyer** [comment]
Hey Max,

This is certainly an issue with opencv. Did your colleague try to install opencv using apt, i.e., apt-get install libopencv-dev etc? I recommend this way as these distributions often come with OpenGL support which is helpful for showing frames at high frame rates. I'm using the default opencv packages in Linux Mint 17.3 (based on Ubuntu 14.04) and everything is working without any problems. Otherwise, you might try to recompile opencv via
cmake -DWITH_IPP=ON -DINSTALL_CREATE_DISTRIB=ON . && make && make install

And sure, the GenericProcessor-related files need to be changed too. Thanks for pointing that out. I updated the description.

Hope this helps,
Arne

**Comment by mmyros** [comment]
Turned out that opencv was indeed installed through repos. I fixed the issue by cloning opencv, running cmake, and copying ~/opencv/3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a to /usr/local/lib/ 

I would attached libippicv.a to help others, but it is too large for github.
