### ISSUE TITLE
Open Ephys GUI crashing

### ISSUE THREAD

**Issue by eliezyer** [arnefmeyer/FrameGrabberPlugin#2]
Hi,

I've successfully installed the Frame Grabber at my current GUI version. It looks great! However, I'm getting a crash at GUI when I try to record, but not when I just hit the play button.
It does create the folder 'frames' in the recording folder, but it contains just one single figure (.jpg) and the timestamps file (.csv).

The following error is returned when I try to record:

"terminate called after throwing an instance of 'std::out_of_range'
      what(): map:at
/bin/openEphys: line 8: 29712 Aborted                                               (core dumped) ./open-ephys"

Any thoughts on how can I solve this?

Best,
Eliezyer

**Comment by arnefmeyer** [comment]
Hi Eliezyer,

This is a general problem with the current GUI version rather than the plugin:
https://github.com/open-ephys/plugin-GUI/issues/67

You have to deactivate recording of the two plugin dummy channels automatically created by the GUI. This should solve the problem. However, let me know if there are any other issues.

Best,
Arne

**Comment by eliezyer** [comment]
Hi Arne,

It did work now. Thanks a lot!

Best,
Eliezyer
